[mypy]
python_version = 3.12
exclude = (?x)(
    ^tests/
  | ^migrations/
  | ^wow_shop/_local\.py$
)

plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
disable_error_code = empty-body
check_untyped_defs = True
implicit_optional = True
strict_optional = True
no_warn_no_return = True
disallow_incomplete_defs = True
disallow_untyped_defs = True

pretty = True
show_error_codes = True
warn_unused_configs = True
warn_unused_ignores = True

[mypy-coloredlogs.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-wow_shop._local]
follow_imports = skip
