"""init schema

Revision ID: ba9390fe80ac
Revises: 
Create Date: 2026-03-14 18:40:51.849769
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9390fe80ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', name='auth_user_status_enum'), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'BOOSTER', 'ADMIN', 'MANAGER', 'OPERATOR', 'CONTENT_MANAGER', name='auth_user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_users')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_users__email'))
    )
    op.create_table('catalog_service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_service_categories.id'], name=op.f('fk_catalog_service_categories__parent_id__catalog_service_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_service_categories')),
    sa.UniqueConstraint('parent_id', 'slug', name=op.f('uq_catalog_service_categories__parent_id_slug'))
    )
    op.create_table('orders_guest_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_guest_contacts'))
    )
    op.create_table('pricing_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('CATEGORY', 'LOT', name='pricing_promotion_scope_type_enum'), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('promo_type', sa.Enum('DISCOUNT_PERCENT', 'DISCOUNT_FIXED', 'TAG_ONLY', name='pricing_promotion_promo_type_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_promotions'))
    )
    op.create_table('auth_admin_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('author_admin_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_admin_id'], ['auth_users.id'], name=op.f('fk_auth_admin_notes__author_admin_id__auth_users')),
    sa.ForeignKeyConstraint(['target_user_id'], ['auth_users.id'], name=op.f('fk_auth_admin_notes__target_user_id__auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_admin_notes'))
    )
    op.create_table('auth_booster_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'DECLINED', name='auth_booster_profile_approval_status_enum'), nullable=False),
    sa.Column('tier', sa.Enum('BOOSTER', 'SUPER_BOOSTER', name='auth_booster_profile_tier_enum'), nullable=False),
    sa.Column('discord_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_auth_booster_profiles__user_id__auth_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_auth_booster_profiles'))
    )
    op.create_table('catalog_service_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_price_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_service_categories.id'], name=op.f('fk_catalog_service_lots__category_id__catalog_service_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_service_lots'))
    )
    op.create_table('notifications_in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_notifications_in_app_notifications__user_id__auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_in_app_notifications'))
    )
    op.create_table('notifications_notification_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'DISCORD', 'TELEGRAM', 'EMAIL', name='notifications_endpoint_channel_enum'), nullable=False),
    sa.Column('endpoint_value', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_notifications_notification_endpoints__user_id__auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_notification_endpoints'))
    )
    op.create_table('notifications_system_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'DISCORD', 'TELEGRAM', 'EMAIL', name='notifications_system_channel_enum'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notifications_system_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['auth_users.id'], name=op.f('fk_notifications_system_notifications__target_user_id__auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_system_notifications'))
    )
    op.create_table('catalog_service_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['catalog_service_lots.id'], name=op.f('fk_catalog_service_options__lot_id__catalog_service_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_service_options'))
    )
    op.create_table('catalog_service_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='catalog_service_page_status_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['catalog_service_lots.id'], name=op.f('fk_catalog_service_pages__lot_id__catalog_service_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_service_pages')),
    sa.UniqueConstraint('lot_id', name=op.f('uq_catalog_service_pages__lot_id'))
    )
    op.create_table('orders_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAYMENT_PENDING', 'PAID', 'NEEDS_ADMIN_REVIEW', 'ASSIGNED', 'ACCEPTED', 'REQUIREMENTS_PENDING', 'IN_PROGRESS', 'DONE', 'CLOSED', 'CANCELED', 'DISPUTED', 'REFUNDED', 'PARTIAL_REFUND', name='orders_order_status_enum'), nullable=False),
    sa.Column('execution_mode', sa.Enum('SELF_PLAY', 'PILOTED', 'ANYDESK', name='orders_order_execution_mode_enum'), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=True),
    sa.Column('guest_contact_id', sa.Integer(), nullable=True),
    sa.Column('booster_user_id', sa.Integer(), nullable=True),
    sa.Column('service_lot_id', sa.Integer(), nullable=False),
    sa.Column('selected_options_json', sa.JSON(), nullable=True),
    sa.Column('price_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booster_user_id'], ['auth_users.id'], name=op.f('fk_orders_orders__booster_user_id__auth_users')),
    sa.ForeignKeyConstraint(['customer_user_id'], ['auth_users.id'], name=op.f('fk_orders_orders__customer_user_id__auth_users')),
    sa.ForeignKeyConstraint(['guest_contact_id'], ['orders_guest_contacts.id'], name=op.f('fk_orders_orders__guest_contact_id__orders_guest_contacts')),
    sa.ForeignKeyConstraint(['paid_by_admin_id'], ['auth_users.id'], name=op.f('fk_orders_orders__paid_by_admin_id__auth_users')),
    sa.ForeignKeyConstraint(['service_lot_id'], ['catalog_service_lots.id'], name=op.f('fk_orders_orders__service_lot_id__catalog_service_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_orders')),
    sa.UniqueConstraint('public_number', name=op.f('uq_orders_orders__public_number'))
    )
    op.create_table('catalog_service_page_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['catalog_service_pages.id'], name=op.f('fk_catalog_service_page_blocks__page_id__catalog_service_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_service_page_blocks')),
    sa.UniqueConstraint('page_id', 'position', name=op.f('uq_catalog_service_page_blocks__page_id_position'))
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_chat_threads__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads')),
    sa.UniqueConstraint('order_id', name=op.f('uq_chat_threads__order_id'))
    )
    op.create_table('orders_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth_users.id'], name=op.f('fk_orders_checkpoints__created_by_user_id__auth_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_orders_checkpoints__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_checkpoints'))
    )
    op.create_table('orders_magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_orders_magic_links__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_magic_links')),
    sa.UniqueConstraint('order_id', name=op.f('uq_orders_magic_links__order_id'))
    )
    op.create_table('orders_order_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('booster_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='orders_order_claim_status_enum'), nullable=False),
    sa.Column('decided_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booster_user_id'], ['auth_users.id'], name=op.f('fk_orders_order_claims__booster_user_id__auth_users')),
    sa.ForeignKeyConstraint(['decided_by_admin_id'], ['auth_users.id'], name=op.f('fk_orders_order_claims__decided_by_admin_id__auth_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_orders_order_claims__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_order_claims'))
    )
    op.create_index(op.f('ix_orders_order_claims__order_id'), 'orders_order_claims', ['order_id'], unique=False)
    op.create_table('payments_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELED', name='payments_payment_status_enum'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_admin_id'], ['auth_users.id'], name=op.f('fk_payments_payments__confirmed_by_admin_id__auth_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_payments_payments__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_payments'))
    )
    op.create_table('payments_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FULL', 'PARTIAL', name='payments_refund_type_enum'), nullable=False),
    sa.Column('amount_eur', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_eur IS NULL OR amount_eur >= 0', name=op.f('ck_payments_refunds__amount_eur_positive')),
    sa.ForeignKeyConstraint(['decided_by_admin_id'], ['auth_users.id'], name=op.f('fk_payments_refunds__decided_by_admin_id__auth_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders_orders.id'], name=op.f('fk_payments_refunds__order_id__orders_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_refunds'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['auth_users.id'], name=op.f('fk_chat_messages__author_user_id__auth_users')),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_messages__thread_id__chat_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_thread', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_participants__thread_id__chat_threads')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_chat_participants__user_id__auth_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_participants')),
    sa.UniqueConstraint('thread_id', 'user_id', name=op.f('uq_chat_participants__thread_id_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    op.drop_table('payments_refunds')
    op.drop_table('payments_payments')
    op.drop_index(op.f('ix_orders_order_claims__order_id'), table_name='orders_order_claims')
    op.drop_table('orders_order_claims')
    op.drop_table('orders_magic_links')
    op.drop_table('orders_checkpoints')
    op.drop_table('chat_threads')
    op.drop_table('catalog_service_page_blocks')
    op.drop_table('orders_orders')
    op.drop_table('catalog_service_pages')
    op.drop_table('catalog_service_options')
    op.drop_table('notifications_system_notifications')
    op.drop_table('notifications_notification_endpoints')
    op.drop_table('notifications_in_app_notifications')
    op.drop_table('catalog_service_lots')
    op.drop_table('auth_booster_profiles')
    op.drop_table('auth_admin_notes')
    op.drop_table('pricing_promotions')
    op.drop_table('orders_guest_contacts')
    op.drop_table('catalog_service_categories')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
